using FinTrack.Models.Entity;
using FinTrack.Models.Enums;
using System.ComponentModel.DataAnnotations;
//V1
namespace FinTrack.Models.DTOs.TransactionDto
{
    //Not adding ID, CreatedAt, UpdatedAt because those will be generated by the system
    public class TransactionCreateDto
    {
        [Required]
        public decimal Amount { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public TransactionType Type { get; set; }
        [Required]
        public PaymentMode PaymentMode { get; set; }
        public string? Description { get; set; }
        [Required]
        public int CategoryId { get; set; }
    
    }
}
