// <auto-generated />
using System;
using FinTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinTrack.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinTrack.Models.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Groceries"
                        });
                });

            modelBuilder.Entity("FinTrack.Models.Entity.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 17, 44, 28, 930, DateTimeKind.Local).AddTicks(8252),
                            Date = new DateTime(2026, 5, 4, 17, 44, 28, 930, DateTimeKind.Local).AddTicks(8238),
                            Description = "Salary",
                            PaymentMode = 3,
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 5, 4, 17, 44, 28, 930, DateTimeKind.Local).AddTicks(8254)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 17, 44, 28, 930, DateTimeKind.Local).AddTicks(8259),
                            Date = new DateTime(2026, 5, 4, 17, 44, 28, 930, DateTimeKind.Local).AddTicks(8257),
                            Description = "Bought Milk and bread",
                            PaymentMode = 3,
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 5, 4, 17, 44, 28, 930, DateTimeKind.Local).AddTicks(8260)
                        });
                });

            modelBuilder.Entity("FinTrack.Models.Entity.Transaction", b =>
                {
                    b.HasOne("FinTrack.Models.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
